<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <RegisterForComInterop>false</RegisterForComInterop>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OrgLens.Core\OrgLens.Core.csproj" />
    <ProjectReference Include="..\OrgLens.Desktop\OrgLens.Desktop.csproj" />
    <Reference Include="Microsoft.Office.Interop.Outlook">
      <HintPath>$(OfficePiaRoot)\Microsoft.Office.Interop.Outlook\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Outlook.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
    <Reference Include="office">
      <HintPath>$(OfficePiaRoot)\office\15.0.0.0__71e9bce111e9429c\OFFICE.DLL</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
